site_name: readme.sbczk.com
site_url: https://readme.sbczk.com

copyright: Copyright &copy; 2025 Tomasz Sobczak

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tomsobpl
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tomaszsobczak/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/tomsobpl

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Links:
    - Buy Me a Coffee: https://buymeacoffee.com/tomsobpl

plugins:
  - blog:
      blog_dir: .
      blog_toc: true
      post_url_date_format: "yyyy/MM"
  - meta
  - tags

theme:
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    - navigation.top
  icon:
    logo: material/rss
  language: en
  name: material
